aliases:
    fleeks: cd ~/.local/share/fleek
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
packages:
    - helix
    - obsidian
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - emacs
    - fish
shell: bash
systems:
    - arch: x86_64
      hostname: fedora
      os: linux
      username: matt
unfree: true
users:
    - email: matt@mattbowen.net
      name: Matt
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: matt
